### ISSUE TITLE
nem2-asset-identifier not found on npm registry

### ISSUE THREAD

**Issue by jacksontungamira** [nemtech/nem2-workshop-nem-applied-to-supply-chain#7]
project cannot npm install nem2-asset-identifier library to identify blockchain assets in no longer available on npm registry

**Comment by dgarcia360** [comment]
Hi @jacksontungamira, thanks for reporting the issue.

We have removed the dependency that was affected and updated the workshop to the latest catapult release.

**Comment by jacksontungamira** [comment]
okay thank you. Let me try to work it out.
